#!/usr/bin/env bash

export MSVCARCH="${MSVCARCH:-64}"
unset CC
unset CXX

# bring in the msvc vars as environment variables so they'll be picked up by wine
set -a
source /etc/vcwine/vcvars$MSVCARCH
set +a

# append the imported windows Path (distinct from PATH) to the WINEPATH
export WINEPATH="$WINEPATH;$Path"
export -n Path

# wine seems to have a max on how long WINEPATH can be
export WINEPATH=${WINEPATH:0:1024}

# something is wonky with the way LINK.EXE reads the %LIB% env var;
# this harmless munging of %LIB% seems to make it happy
if [[ $VCINSTALLDIR = *"2017"* ]]; then
    export LIB="$LIB$LIB"
elif [[ $VCINSTALLDIR = *"14.0"* ]]; then
    export LIB="${LIB//;/;$VCINSTALLDIR;}"
elif [[ $VCINSTALLDIR = *"12.0"* ]]; then
    export LIB="${LIB//;/;$VCINSTALLDIR;}"
fi

# pass along script args to wine
wine64 "$@"
